# Generated by Django 3.2.7 on 2022-04-11 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recruitment_type",
                    models.CharField(
                        choices=[("pve", "Pve"), ("casual", "Casual")],
                        default="casual",
                        max_length=10,
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[("text", "Text"), ("radio", "Radio")],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("discord", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
