# Generated by Django 3.2.7 on 2022-04-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("multiline", "Multiline"),
                    ("radio", "Radio"),
                ],
                default="text",
                max_length=10,
            ),
        ),
    ]
