# Generated by Django 3.2.7 on 2022-09-23 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raid_name", models.CharField(max_length=255)),
                ("raid_key", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
