# Generated by Django 3.2.7 on 2022-04-11 15:43

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
