# Generated by Django 3.2.7 on 2022-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_alter_page_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
