# Generated by Django 3.2.7 on 2022-04-08 06:33

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("icon", models.CharField(max_length=60)),
                ("color", models.CharField(max_length=60)),
                (
                    "link",
                    models.CharField(
                        max_length=255, validators=[django.core.validators.URLValidator]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
