# Generated by Django 3.2.7 on 2022-04-08 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("Ojciec Barbarzyńca", "Guild Master"),
                            ("Szaman", "Officer"),
                            ("Raid Leader", "Raid Leader"),
                        ],
                        max_length=18,
                    ),
                ),
                ("discord", models.CharField(max_length=37)),
                ("server", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "character_name",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "wow_image",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
