# Generated by Django 3.2.7 on 2022-05-13 07:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "leader",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leader",
                        related_query_name="leader",
                        to="contact.contact",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GroupTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RaidDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Poniedziałek"),
                            ("tuesday", "Wtorek"),
                            ("wednesday", "Środa"),
                            ("thursday", "Czwartek"),
                            ("friday", "Piątek"),
                            ("saturday", "Sobota"),
                            ("sunday", "Niedziela"),
                        ],
                        max_length=9,
                    ),
                ),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="group.group"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="group",
            name="tags",
            field=models.ManyToManyField(
                related_name="tags", related_query_name="tags", to="group.GroupTag"
            ),
        ),
    ]
