# Generated by Django 3.2.7 on 2022-05-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="raidday",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
