# Generated by Django 3.2.7 on 2022-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0002_raidday_is_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="grouptag",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
