# Generated by Django 3.2.7 on 2022-05-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0003_auto_20220513_0735"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raidday",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raid_days",
                related_query_name="raid_days",
                to="group.group",
            ),
        ),
    ]
